# Generated by Django 5.1.3 on 2024-12-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
